runtime: python
env: flex

runtime_config:
  operating_system: "ubuntu22"
  python_version: "3.10"

entrypoint: gunicorn --bind :$PORT app.app:app

handlers:
- url: /
  script: auto

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2