# C:/workspace/github/python/sample_gcp/Dockerfile.txt

FROM python:3.11.10-slim

WORKDIR /gcpFlaskApp

COPY . /gcpFlaskApp

RUN apt-get update
RUN apt-get install ffmpeg libsm6 libxext6 --yes
RUN pip install -r requirements.txt

CMD ["python", "app/app.py"]